### ISSUE TITLE
Failed at the locus@2.0.1 postinstall script 'mkdir ./histories'.

### ISSUE THREAD

**Issue by vasunep0306** [buildize/locus#18] opened 2017-10-06 22:47 UTC
[npm-debug.log](https://github.com/buildize/locus/files/1364064/npm-debug.log)

**Comment by rgrannell1** [comment] 2017-10-08 14:06
Hi, 
I'm submitting a PR to fix this at the moment, the error is caused by the use of "mkdir" on Windows.

**Comment by glenpike** [comment] 2017-11-07 09:42
Ditto with Ubuntu 16.04

```
> locus@2.0.1 postinstall /home/ski/swoop/codebase/system/campaign-builder/server/repo/node_modules/locus
> mkdir ./histories

mkdir: cannot create directory ‘./histories’: File exists
```
On linux `mkdir -p` will behave better https://linux.die.net/man/1/mkdir

**Comment by glenpike** [comment] 2017-11-07 10:26
@rgrannell1 - are you able to check the PR I made on Windows?

**Comment by rgrannell1** [comment] 2017-11-08 22:28
Hi @glenpike, I'll test that code at work tomorrow

**Comment by MarkCog** [comment] 2018-01-13 19:55
Same problem.  Any help would be appreciated...

**Comment by jlbets123** [comment] 2018-02-17 22:16
Same here =(

**Comment by glenpike** [comment] 2018-02-19 13:16
For those needing help: the workaround would be to remove the histories directory before installing locus.

**Comment by HuangChaoWH** [comment] 2018-03-24 10:33
Change the postinstall, remove ./ , then it work on both Linux and Windows
    "postinstall": "mkdir histories"

**Comment by glenpike** [comment] 2018-03-24 10:45
Won't this still break if the histories directory exists already?

If someone could test the pr #bbaad1b on Windows, maybe that could be merged.

On 24 March 2018 10:33:35 GMT+00:00, HuangChaoWH <notifications@github.com> wrote:
>Change the postinstall, remove ./ , then it work on both Linux and
>Windows
>    "postinstall": "mkdir histories"
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/buildize/locus/issues/18#issuecomment-375868184

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by HuangChaoWH** [comment] 2018-03-24 11:15
Thank you for your suggestion, I just make a private package.
@huangchaowh/locus
it works on Windows.

**Comment by glenpike** [comment] 2018-03-26 10:17
Cool, so the PR is good on Windows?  - Can you add a comment on https://github.com/buildize/locus/pull/19 and maybe that can get merged in by @alidavut ?

**Comment by ThiagoMArc** [comment] 2018-04-14 16:30
hello, i'm also facing this issue on Windows. After cloning a repository from github and run npm install i get this error message at the end of the process

**Comment by curtispuetz** [comment] 2018-10-03 01:46
> Thank you for your suggestion, I just make a private package.
> `@huangchaowh/locus`
> it works on Windows.

@HuangChaoWH This works on windows. I am able to install. But I can only use the debugger once. Then if I try to use it again a second time there is an error at `eval(require('@huangchaowh/locus'))`. I can work around this by navigating to the histories directory and deleting the 1 file in there that contains the commands of the last debug. Once this is deleted I can use the debugger again.

**Comment by nchulani2** [comment] 2019-04-10 04:14
One solution is to install a previous version of locus. 
Use: "npm install -D locus@2.0.0

**Comment by tinchonapa** [comment] 2019-04-29 16:34
I didn't have a './histories' folder and I was still getting the error. By installing the previous version like @nchulani2  suggested, it worked.

**Comment by Hashamjavedofficial** [comment] 2019-07-07 14:52
> One workaround is to install a previous version of locus.
> Use: "npm install -D locus@2.0.0"

Thanks it worked for me :D

**Comment by joshmakar** [comment] 2019-07-24 18:14
Installing locus 2.0.0 worked for me. Would love to hear when there's a fix for the latest version.

**Closed** 2019-11-09 19:03 UTC
